on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Deploy to Yandex Cloud Object Storage
      uses: paulvstrashnov/yandex-s3-upload-action@main
      with:
        accessKeyId: ${{ secrets.YC_ACCESS_KEY_ID }}
        secretAccessKey: ${{ secrets.YC_SECRET_ACCESS_KEY }}
        bucket: ${{ secrets.BUCKET }}
        localPath: "./assets"
        remotePath: "./assets"
        clearBucket: false
